sudo: required
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker build -t cosmix/klitikizer .
  - docker run -d cosmix/klitikizer 'cd /klitikizer; ./vendor/phpunit tests'
install:
  - composer install
